import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const dataDir = path.join(__dirname, "data");
const encoded = [1, 2, 3, 4]
  .map((part) => fs.readFileSync(path.join(dataDir, `b2c1-speaking-models-${part}.txt`), "utf8").trim())
  .join("");
const payload = JSON.parse(zlib.gunzipSync(Buffer.from(encoded, "base64")).toString("utf8"));

function jsObject(name, value) {
  return `const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

const generated = [
  "// Generated by scripts/patchB2C1SpeakingModels.mjs. Do not edit by hand.",
  "",
  jsObject("B2_SPEAKING_ANSWERS", payload.B2),
  jsObject("C1_SPEAKING_ANSWERS", payload.C1),
  `function attach(slides = [], answersByDay = {}) {
  for (const slide of slides) {
    const questions = Array.isArray(slide.studentQuestionsDe) ? slide.studentQuestionsDe : [];
    const answers = answersByDay[Number(slide.dayNumber)] || [];
    slide.speakingModels = questions.map((questionDe, index) => ({
      questionDe,
      modelAnswerDe: answers[index] || "",
    }));
  }
}

export function attachAdvancedSpeakingModels({ b2Slides = [], c1Slides = [] } = {}) {
  // B2 and C1 now own direct speaking models inside their canonical presenter data.
  // Keep this compatibility hook as a no-op so prebuild cannot overwrite them.
  void b2Slides;
  void c1Slides;
}
`,
].join("\n");

const generatedPath = path.join(root, "src/data/advancedSpeakingModels.js");
if (!fs.existsSync(generatedPath) || fs.readFileSync(generatedPath, "utf8") !== generated) {
  fs.writeFileSync(generatedPath, generated, "utf8");
}

function patchFile(relativePath, replacements) {
  const filePath = path.join(root, relativePath);
  let content = fs.readFileSync(filePath, "utf8");
  let changed = false;

  for (const { from, to } of replacements) {
    if (content.includes(to)) continue;
    if (!content.includes(from)) {
      throw new Error(`Unable to patch ${relativePath}: expected text not found: ${from}`);
    }
    content = content.replace(from, to);
    changed = true;
  }

  if (changed) fs.writeFileSync(filePath, content, "utf8");
}

{
  const teachingSlidesPath = path.join(root, "src/data/teachingSlides.js");
  let teachingSlidesSource = fs.readFileSync(teachingSlidesPath, "utf8");
  const speakingImport = 'import { attachAdvancedSpeakingModels } from "./advancedSpeakingModels.js";';
  if (!teachingSlidesSource.includes(speakingImport)) {
    const c1Import = 'import { c1PresenterSlides } from "./c1PresenterSlides.js";';
    if (!teachingSlidesSource.includes(c1Import)) throw new Error("Advanced speaking-model import anchor missing");
    teachingSlidesSource = teachingSlidesSource.replace(c1Import, c1Import + "\n" + speakingImport);
    fs.writeFileSync(teachingSlidesPath, teachingSlidesSource, "utf8");
  }
}

patchFile("src/data/teachingSlides.js", [
  {
    from: 'import { getSlideQuestionSet } from "./teachingSlideQuestionDictionary.js";',
    to: 'import { getSlideQuestionSet } from "./teachingSlideQuestionDictionary.js";\nimport { getCourseTaskDay } from "./courseSessionGroups.js";',
  },
  {
    from: "const curatedSlides = [",
    to: "attachAdvancedSpeakingModels({ b2Slides: b2PresenterSlides, c1Slides: c1PresenterSlides });\n\nconst curatedSlides = [",
  },
  {
    from: 'function createTemplateSlide(level, entry, lessonNumber) {\n  const levelLabel = level.toUpperCase();',
    to: 'function createTemplateSlide(level, entry, lessonNumber) {\n  const levelLabel = level.toUpperCase();\n  const dayLabel = levelLabel === "A1" ? "Day" : "Lesson";',
  },
  {
    from: '    day: `Lesson ${lessonNumber}`,',
    to: '    day: `${dayLabel} ${lessonNumber}`,',
  },
  {
    from: '    title: `${levelLabel} Lesson ${lessonNumber} · ${entry.de}`,',
    to: '    title: `${levelLabel} ${dayLabel} ${lessonNumber} · ${entry.de}`,',
  },
  {
    from: 'function buildLevelSlides(level) {\n  const entries = Object.values(courseDictionary[level] || {}).sort((left, right) => compareChapter(left.chapter, right.chapter));\n  return entries.map((entry, index) => createTemplateSlide(level, entry, index + 1));\n}',
    to: 'function buildLevelSlides(level) {\n  const entries = Object.values(courseDictionary[level] || {}).sort((left, right) => compareChapter(left.chapter, right.chapter));\n  return entries.map((entry, index) => {\n    const lessonNumber = String(level || "").toUpperCase() === "A1"\n      ? getCourseTaskDay("A1", entry.assignment_id, index)\n      : index + 1;\n    return createTemplateSlide(level, entry, lessonNumber);\n  });\n}',
  },
  {
    from: 'const a1Slides = buildLevelSlides("A1").map((slide) => curatedSlidesByAssignment[slide.assignmentId] || slide);',
    to: 'const a1Slides = buildLevelSlides("A1").map((slide, index) => {\n  const resolved = curatedSlidesByAssignment[slide.assignmentId] || slide;\n  const dayNumber = getCourseTaskDay("A1", resolved.assignmentId, index);\n  const titleBody = String(resolved.title || "")\n    .replace(/^A1\\s+(?:Lesson|Day)\\s+\\d+\\s*·\\s*/i, "")\n    .replace(/^A1\\s*·\\s*/i, "")\n    .trim();\n  return {\n    ...resolved,\n    day: `Day ${dayNumber}`,\n    dayNumber,\n    title: titleBody ? `A1 Day ${dayNumber} · ${titleBody}` : `A1 Day ${dayNumber}`,\n  };\n});',
  },
]);

patchFile("src/utils/teachingPresenter.js", [
  {
    from: 'requiresQuestionModel: ["A2", "B1"].includes(String(slide.course || "").toUpperCase()),',
    to: 'requiresQuestionModel: ["A2", "B1", "B2", "C1", "C2"].includes(level),',
  },
]);

const b1RegressionPath = path.join(root, "tests/b1-speaking-model-answers.test.js");
if (fs.existsSync(b1RegressionPath)) {
  patchFile("tests/b1-speaking-model-answers.test.js", [
    {
      from: 'for (const level of ["A1", "B2", "C1"]) {',
      to: 'for (const level of ["A1"]) {',
    },
  ]);
}

{
  const presenterPath = path.join(root, "src/utils/teachingPresenter.js");
  const presenterSource = fs.readFileSync(presenterPath, "utf8");
  const requiredPresenterMarkers = [
    'if (level === "B2") {',
    'function buildB2FocusedTask',
    'type: "b2-grammar"',
    'title: "Sprechen · entwickeln, vergleichen und reagieren"',
    'if (level === "C1") {',
    'id: "focus"',
    'type: "c1-grammar"',
    'title: "Sprechen · argumentieren und reagieren"',
    'title: "Schreibbrücke · Argument in Absatzform"',
  ];
  for (const marker of requiredPresenterMarkers) {
    if (!presenterSource.includes(marker)) {
      throw new Error("B2/C1 teaching-spine marker missing: " + marker);
    }
  }

  const weeklyChallengeStart = presenterSource.indexOf("function buildAdvancedWeeklyChallenge");
  const weeklyChallengeEnd = presenterSource.indexOf("function lessonSummaryObjective", weeklyChallengeStart);
  const weeklyChallengeBlock = weeklyChallengeStart >= 0 && weeklyChallengeEnd > weeklyChallengeStart
    ? presenterSource.slice(weeklyChallengeStart, weeklyChallengeEnd)
    : "";
  if (!weeklyChallengeBlock.includes("return null;")) {
    throw new Error("Legacy B2 weekly challenge must remain disabled.");
  }
}

console.log("Canonical A1 teaching-slide day mapping is patched; B2/C1 keep direct curriculum speaking models.");
await import("./patchC2CourseStyle.mjs");
