import fs from "node:fs";

const presenterPath = new URL("../src/utils/teachingPresenter.js", import.meta.url);

const A2_KNOWLEDGE_TEXTS = [
  { assignmentId: "A2-1.1", path: "src/data/a2WorkbookAlignedSlides.js", text: "Small Talk beginnt oft mit einfachen Themen wie Familie, Arbeit, Sprachen, Freizeit oder Wetter. Wichtig ist nicht nur, kurze Antworten zu geben, sondern das Gespräch weiterzuführen. Man kann einen Grund mit „weil“ oder „denn“ nennen und eine Folge mit „deshalb“ ausdrücken. Zum Beispiel: Ich lerne Deutsch, weil ich später in Deutschland arbeiten möchte. Ich arbeite viel, deshalb entspanne ich mich am Wochenende. Gute Gesprächspartner stellen auch Rückfragen und reagieren auf das, was die andere Person sagt." },
  { assignmentId: "A2-1.2", path: "src/data/a2WorkbookAlignedSlides.js", text: "Wenn wir eine Person beschreiben, sprechen wir meistens über Aussehen, Kleidung und Charakter. Nach „sein“ bleibt das Adjektiv ohne Endung: Sie ist freundlich. Vor einem Nomen braucht das Adjektiv aber eine Endung: eine freundliche Kollegin, ein netter Nachbar oder einen schwarzen Pullover. Für eine gute Beschreibung verbindet man mehrere Informationen: Wer ist die Person? Wie sieht sie aus? Was trägt sie? Wie ist ihr Charakter? Am Ende kann man die eigene Meinung nennen und mit „weil“ begründen." },
  { assignmentId: "A2-1.3", path: "src/data/a2WorkbookAlignedSlides.js", text: "Vergleiche helfen uns, zwischen zwei oder mehreren Möglichkeiten zu entscheiden. Mit „so ... wie“ sagen wir, dass zwei Dinge gleich sind: Der Bus ist so schnell wie die Bahn. Mit dem Komparativ und „als“ zeigen wir einen Unterschied: Die Bahn ist schneller als der Bus. Für die stärkste Form benutzen wir oft „am“ plus Superlativ: Das Flugzeug ist am schnellsten. Einige Formen sind unregelmäßig, zum Beispiel gut – besser – am besten. Ein sinnvoller Vergleich nennt immer ein klares Kriterium und eine Begründung." },
  { assignmentId: "A2-2.4", path: "src/data/a2WorkbookAlignedSlides.js", text: "Bei einer Verabredung braucht man mehr als nur einen Ort. Ein guter Plan enthält Aktivität, Treffpunkt, Tag, Uhrzeit und oft auch die Anreise. Bei Ortsangaben ist die Frage wichtig: „Wo?“ beschreibt eine Position und steht häufig mit Dativ, zum Beispiel im Café oder am Bahnhof. „Wohin?“ beschreibt eine Richtung, zum Beispiel ins Café oder an den Bahnhof. Wenn ein Vorschlag nicht passt, kann man höflich eine Alternative machen: Passt dir Samstag nicht? Dann können wir uns am Sonntag treffen." },
  { assignmentId: "A2-2.5", path: "src/data/a2WorkbookAlignedSlides.js", text: "Freizeitaktivitäten erzählen viel über unseren Alltag. Im Deutschen gibt es dabei viele trennbare Verben, zum Beispiel aufstehen, einkaufen, fernsehen oder ausgehen. Im Hauptsatz steht die Vorsilbe am Ende: Ich kaufe am Samstag ein. Mit einem Modalverb bleibt das Verb zusammen und steht als Infinitiv am Ende: Ich möchte am Samstag einkaufen. Für eine natürliche Antwort nennt man nicht nur die Aktivität, sondern auch Zeit, Personen und Gründe: Am Wochenende gehe ich gern spazieren, weil ich mich dabei entspannen kann." },
  { assignmentId: "A2-3.6", path: "src/data/a2WorkbookAlignedSlidesDays6To10.js", text: "Bei Möbeln und Räumen ist der Unterschied zwischen „Wo?“ und „Wohin?“ besonders wichtig. „Wo?“ beschreibt eine feste Position und braucht bei Wechselpräpositionen den Dativ: Das Sofa steht neben dem Fenster. „Wohin?“ beschreibt eine Bewegung zu einem Ziel und braucht den Akkusativ: Ich stelle das Sofa neben das Fenster. Typische Wechselpräpositionen sind an, auf, hinter, in, neben, über, unter, vor und zwischen. Eine gute Raumbeschreibung nennt den Raum, wichtige Möbel, ihre Position und vielleicht eine Veränderung, die man machen möchte." },
  { assignmentId: "A2-3.7", path: "src/data/a2WorkbookAlignedSlidesDays6To10.js", text: "Wer eine Wohnung sucht, achtet meist auf Größe, Lage, Preis und Ausstattung. In Anzeigen stehen deshalb Wörter wie Kaltmiete, Nebenkosten, Warmmiete, Kaution, Balkon oder Einbauküche. Relativsätze helfen, eine Wohnung genauer zu beschreiben: Ich suche eine Wohnung, die ruhig liegt. Das Haus, das einen Garten hat, gefällt mir. Das Relativpronomen richtet sich nach dem Nomen, und das Verb steht im Relativsatz am Ende. Bei einer Anfrage an den Vermieter sollte man außerdem nach Verfügbarkeit, Kosten und einem Besichtigungstermin fragen." },
  { assignmentId: "A2-3.8", path: "src/data/a2WorkbookAlignedSlidesDays6To10.js", text: "Ein Rezept erklärt Schritt für Schritt, wie ein Gericht zubereitet wird. Man nennt zuerst die Zutaten und dann die einzelnen Arbeitsschritte in einer logischen Reihenfolge. Für Anweisungen benutzt man oft den Imperativ: Schneide die Tomaten. Gib das Öl in die Pfanne. Mischen Sie alles gut. Wörter wie zuerst, dann, danach und zum Schluss machen den Ablauf verständlich. Beim Sprechen über Essen kann man außerdem Mengen und Vorlieben nennen. Ein gutes Rezept ist so klar, dass eine andere Person das Gericht ohne zusätzliche Erklärung nachkochen kann." },
  { assignmentId: "A2-4.9", path: "src/data/a2WorkbookAlignedSlidesDays6To10.js", text: "Über einen vergangenen Urlaub sprechen wir häufig im Perfekt. Viele Verben bilden das Perfekt mit „haben“: Ich habe ein Museum besucht. Verben der Bewegung oder Zustandsänderung stehen oft mit „sein“: Wir sind nach Berlin gefahren. Ich bin früh aufgestanden. Für eine interessante Urlaubserzählung nennt man Ort, Reisezeit, Verkehrsmittel, Unterkunft und Aktivitäten. Danach kann man sagen, was besonders schön oder schwierig war. Zeitangaben wie letztes Jahr, am ersten Tag oder danach helfen, die Erlebnisse in eine klare Reihenfolge zu bringen." },
  { assignmentId: "A2-4.10", path: "src/data/a2WorkbookAlignedSlidesDays6To10.js", text: "Traditionelle Feste zeigen viel über die Kultur eines Landes oder einer Region. Man kann erklären, wo und wann ein Fest stattfindet, was die Menschen dort machen, welche Kleidung oder Musik typisch ist und warum das Fest wichtig ist. Bei Erzählungen über früher begegnen uns häufig Präteritumformen wie war, hatte, konnte oder musste. Zum Beispiel: Früher war das Fest kleiner, aber heute kommen viele Besucher. Eine gute Präsentation verbindet Fakten mit persönlichen Eindrücken und erklärt auch, was Touristen dort sehen oder erleben können." },
  { assignmentId: "A2-4.11", path: "src/data/a2WorkbookAlignedSlidesDays11To15.js", text: "Bei Verkehrsmitteln vergleichen wir oft Preis, Geschwindigkeit, Komfort, Sicherheit und Umwelt. Dafür brauchen wir Komparativ und Superlativ: Der Zug ist schneller als der Bus. Das Fahrrad ist günstiger als das Auto. Für lange Strecken ist das Flugzeug oft am schnellsten. Manche Formen sind unregelmäßig, zum Beispiel gut – besser – am besten oder gern – lieber – am liebsten. Eine gute Empfehlung hängt von der Situation ab. Für kurze Wege kann das Fahrrad praktisch sein, während für eine lange Reise der Zug bequemer sein kann." },
  { assignmentId: "A2-5.12", path: "src/data/a2WorkbookAlignedSlidesDays11To15.js", text: "Ein Traumberuf passt zu den eigenen Interessen, Fähigkeiten und Zielen. Mit „möchten“ sprechen wir höflich über Wünsche, mit „wollen“ über eine stärkere Absicht und mit „können“ über Fähigkeiten. Das zweite Verb steht als Infinitiv am Ende: Ich möchte als Designerin arbeiten. Gründe kann man mit „weil“ erklären: Ich möchte Lehrerin werden, weil ich gern mit Menschen arbeite. Nach Meinungen wie „Ich denke“ oder „Ich glaube“ folgt oft ein dass-Satz: Ich denke, dass gute Kommunikation in diesem Beruf wichtig ist." },
  { assignmentId: "A2-5.13", path: "src/data/a2WorkbookAlignedSlidesDays11To15.js", text: "Ein Vorstellungsgespräch ist ein formelles Gespräch zwischen einem Unternehmen und einer Bewerberin oder einem Bewerber. Man stellt sich kurz vor, spricht über Ausbildung, Erfahrung, Stärken und Motivation und beantwortet Fragen zum Beruf. Für frühere Fähigkeiten oder Pflichten kann man Formen wie konnte, musste und wollte benutzen: In meinem letzten Job musste ich viele Kunden beraten. Ich konnte selbstständig arbeiten. Gute Antworten sind konkret und kurz. Am Ende darf man selbst Fragen stellen, zum Beispiel zu Arbeitszeiten, Aufgaben, Team oder Weiterbildung." },
  { assignmentId: "A2-5.14", path: "src/data/a2WorkbookAlignedSlidesDays11To15.js", text: "Karriere bedeutet nicht nur eine höhere Position, sondern auch neue Fähigkeiten, Verantwortung und persönliche Ziele. Mit „um ... zu“ können wir einen Zweck ausdrücken, wenn das Subjekt gleich bleibt: Ich besuche einen Kurs, um meine Deutschkenntnisse zu verbessern. Wenn zwei verschiedene Personen handeln, benutzt man oft „damit“: Die Firma bietet Schulungen an, damit die Mitarbeiter neue Fähigkeiten lernen. Eine gute Karriereplanung nennt den aktuellen Stand, das nächste Ziel und konkrete Schritte wie Weiterbildung, Praktikum, Sprachkurs oder zusätzliche Berufserfahrung." },
  { assignmentId: "A2-6.15", path: "src/data/a2WorkbookAlignedSlidesDays11To15.js", text: "Sport kann Gesundheit, Ausdauer und Wohlbefinden verbessern. Wenn eine Aktivität in der Vergangenheit begonnen hat und bis heute weitergeht, benutzen wir „seit“ mit Dativ und meistens Präsens: Ich spiele seit drei Jahren Fußball. Sie trainiert seit einem Monat im Fitnessstudio. Man kann außerdem über Häufigkeit, Trainingsort, Mannschaft oder persönliche Ziele sprechen. Eine gute Sportbeschreibung beantwortet Fragen wie: Was mache ich? Seit wann? Wie oft? Mit wem? Warum gefällt mir der Sport? So entsteht mehr als nur eine Liste von Sportarten." },
  { assignmentId: "A2-6.16", path: "src/data/a2WorkbookAlignedSlidesDays16To20.js", text: "Wohlbefinden hängt oft von Schlaf, Bewegung, Ernährung, Pausen und sozialen Kontakten ab. Viele Verben zu diesem Thema sind reflexiv: Ich entspanne mich. Du fühlst dich besser. Wir treffen uns mit Freunden. Das Reflexivpronomen passt zur Person: mich, dich, sich, uns, euch, sich. Wenn man sich nicht gut fühlt, kann man Symptome genau beschreiben, zum Beispiel Kopfschmerzen, Husten oder Müdigkeit. Für eine gute Gesundheitsroutine ist es hilfreich, auf den Körper zu achten und rechtzeitig Pausen oder ärztliche Hilfe einzuplanen." },
  { assignmentId: "A2-6.17", path: "src/data/a2WorkbookAlignedSlidesDays16To20.js", text: "In der Apotheke beschreibt man zuerst das Problem und fragt dann nach einer passenden Empfehlung. Modalverben sind dabei sehr nützlich. Mit „können“ fragt man höflich: Können Sie mir etwas gegen Husten empfehlen? Mit „sollen“ fragt man nach einem Rat: Soll ich die Tabletten nach dem Essen nehmen? „Müssen“ beschreibt eine Notwendigkeit: Ich muss das Medikament zweimal täglich nehmen. Wichtig sind auch Fragen zu Dosierung, Dauer und möglichen Nebenwirkungen. Bei starken oder lange anhaltenden Beschwerden sollte man ärztlichen Rat suchen." },
  { assignmentId: "A2-7.18", path: "src/data/a2WorkbookAlignedSlidesDays16To20.js", text: "Bei einem Anruf bei der Bank sollte man das Problem klar und höflich erklären. Häufige Situationen sind eine gesperrte Karte, eine unbekannte Zahlung, eine Überweisung oder eine Frage zum Konto. Mit „könnten“ klingt eine Bitte höflicher: Könnten Sie bitte meine Karte prüfen? Auch „ich würde gern“ ist nützlich: Ich würde gern wissen, warum die Zahlung nicht funktioniert. Vor dem Anruf sollte man wichtige Informationen bereithalten, aber sensible Daten nur über sichere Wege weitergeben. Am Ende wiederholt man die vereinbarte Lösung oder den nächsten Schritt." },
  { assignmentId: "A2-7.19", path: "src/data/a2WorkbookAlignedSlidesDays16To20.js", text: "Beim Einkaufen entscheiden Menschen nach Preis, Qualität, Bequemlichkeit und Herkunft. Im Supermarkt findet man viele Produkte an einem Ort, während Wochenmärkte oft regionale Lebensmittel anbieten. Manche kaufen lieber online ein, denn das spart Zeit. Andere gehen gern ins Geschäft, denn dort können sie Produkte direkt sehen oder anprobieren. Für nachhaltiges Einkaufen kann man Mehrwegtaschen benutzen, regionale Produkte wählen und nur das kaufen, was man wirklich braucht. Mit „oder“ vergleicht man Möglichkeiten, mit „denn“ erklärt man einen Grund für die eigene Entscheidung." },
  { assignmentId: "A2-7.20", path: "src/data/a2WorkbookAlignedSlidesDays16To20.js", text: "Eine Reklamation ist erfolgreicher, wenn sie ruhig, konkret und höflich formuliert ist. Zuerst beschreibt man das Produkt oder die Dienstleistung und nennt dann das genaue Problem. Danach erklärt man, was man erwartet: Reparatur, Umtausch, Ersatz oder Rückerstattung. Hilfreiche Sätze sind: Leider funktioniert das Gerät nicht. Ich habe es gestern gekauft. Könnten Sie es bitte umtauschen? Belege wie Rechnung oder Kassenbon sind oft wichtig. Eine gute Beschwerde trennt Fakten von Emotionen und nennt am Ende eine klare, realistische Lösung." },
  { assignmentId: "A2-8.21", path: "src/data/a2WorkbookAlignedSlidesDays21To24.js", text: "Ein gutes Wochenende lässt sich leichter planen, wenn man Hauptplan und Alternative vorbereitet. Mit „wenn“ und „falls“ beschreibt man Bedingungen: Wenn das Wetter gut ist, gehen wir in den Park. Falls es regnet, bleiben wir zu Hause. Mit „ob“ formuliert man eine indirekte Ja-Nein-Frage: Ich weiß noch nicht, ob meine Freunde Zeit haben. In diesen Nebensätzen steht das Verb am Ende. Ein vollständiger Wochenendplan enthält Aktivitäten, Personen, Zeiten und einen Treffpunkt. So kann man schnell reagieren, wenn sich etwas ändert." },
  { assignmentId: "A2-8.22", path: "src/data/a2WorkbookAlignedSlidesDays21To24.js", text: "Für feste Pläne in der nahen Zukunft benutzt man im Deutschen sehr oft das Präsens zusammen mit einer Zeitangabe: Morgen treffe ich meine Freundin. Am Donnerstag arbeite ich bis 17 Uhr. Wenn die Zeitangabe zuerst steht, bleibt das Verb auf Position zwei. Mit „können“ spricht man über Verfügbarkeit, mit „müssen“ über Pflichten: Am Mittwoch kann ich nicht kommen. Um 18 Uhr muss ich zum Deutschkurs gehen. Eine gute Wochenplanung verbindet Arbeit, Termine, Freizeit und wichtige Aufgaben realistisch miteinander." },
  { assignmentId: "A2-9.23", path: "src/data/a2WorkbookAlignedSlidesDays21To24.js", text: "Für den Arbeits- oder Schulweg sind Präpositionen besonders wichtig. Mit einem Verkehrsmittel benutzen wir meistens „mit“ plus Dativ: Ich fahre mit dem Bus zur Arbeit. Für Personen oder bestimmte Ziele steht oft „zu“ plus Dativ: Ich gehe zum Arzt oder zur Schule. Bei Städten und Ländern ohne Artikel benutzen wir „nach“: Ich fahre nach Berlin. Beim Vergleichen von Verkehrsmitteln spielen Zeit, Kosten, Komfort und Umwelt eine Rolle. Ein guter Weg ist nicht für alle Menschen gleich, sondern hängt von Entfernung und Situation ab." },
  { assignmentId: "A2-9.24", path: "src/data/a2WorkbookAlignedSlidesDays21To24.js", text: "Bei einer Urlaubsplanung entscheidet man zuerst über Reiseziel, Transport, Unterkunft, Dauer und Aktivitäten. Für Reiseziele benutzt man unterschiedliche Präpositionen: nach Berlin, nach Ghana, in die Schweiz, ans Meer oder auf eine Insel. Mit „möchte“ kann man Wünsche ausdrücken: Ich möchte im Sommer nach München reisen. Mit „werden“ kann man einen zukünftigen Plan formulieren: Wir werden dort eine Woche bleiben. Eine gute Planung berücksichtigt auch Budget, Dokumente, Wetter und Reservierungen. So wird aus einem Wunsch ein konkreter Reiseplan." },
  { assignmentId: "A2-9.25", path: "src/data/a2WorkbookAlignedSlidesDays25To28.js", text: "Ein Tagesablauf wird verständlich, wenn die Ereignisse in einer klaren Reihenfolge stehen. Zeitangaben wie morgens, um sieben Uhr, am Nachmittag und abends zeigen, wann etwas passiert. Trennbare Verben werden im Hauptsatz getrennt: Ich stehe um sechs Uhr auf. Abends sehe ich fern. Wörter wie dann, danach und später verbinden die einzelnen Schritte. Wenn eines dieser Wörter am Satzanfang steht, folgt direkt das Verb: Danach frühstücke ich. Eine gute Beschreibung zeigt Morgenroutine, Arbeit oder Schule, Nachmittag und Abend." },
  { assignmentId: "A2-10.26", path: "src/data/a2WorkbookAlignedSlidesDays25To28.js", text: "Gefühle entstehen oft durch bestimmte Situationen. Mit einem wenn-Satz kann man Situation und Gefühl verbinden: Ich bin nervös, wenn ich eine Prüfung habe. Wenn ich gute Nachrichten bekomme, bin ich froh. Im wenn-Satz steht das Verb am Ende. Wenn der Nebensatz zuerst steht, beginnt der Hauptsatz mit dem Verb: Wenn ich gestresst bin, mache ich eine Pause. Für eine gute Beschreibung nennt man nicht nur das Gefühl, sondern auch den Grund oder die Reaktion. So kann man Freude, Angst, Enttäuschung oder Stress genauer erklären." },
  { assignmentId: "A2-10.27", path: "src/data/a2WorkbookAlignedSlidesDays25To28.js", text: "Digitale Kommunikation ist schnell und praktisch, aber sie hat auch Nachteile. Menschen schreiben Nachrichten, führen Videoanrufe, senden Dateien oder organisieren Termine online. Mit dass-Sätzen kann man eine Meinung ausdrücken: Ich finde, dass Messenger sehr praktisch sind. Ich glaube, dass persönliche Gespräche trotzdem wichtig bleiben. Im dass-Satz steht das Verb am Ende. Beim Thema digitale Kommunikation sollte man auch an Datenschutz, Passwörter und private Informationen denken. Nicht jede Nachricht muss sofort beantwortet werden, und sensible Daten gehören nicht in unsichere Chats." },
  { assignmentId: "A2-10.28", path: "src/data/a2WorkbookAlignedSlidesDays25To28.js", text: "Über die Zukunft kann man mit „möchte“, „will“ oder dem Futur I sprechen. Futur I besteht aus „werden“ und einem Infinitiv am Satzende: Ich werde nächstes Jahr einen Deutschkurs machen. Für feste Pläne reicht oft auch Präsens mit Zeitangabe: Im Oktober beginne ich eine Ausbildung. Eine gute Zukunftsplanung umfasst verschiedene Bereiche, zum Beispiel Beruf, Bildung, Familie, Reisen, Gesundheit und persönliche Ziele. Wichtig ist, konkrete Schritte zu nennen. Ein Ziel wird realistischer, wenn man weiß, was man zuerst, danach und später tun möchte." }
];

function replaceOnce(source, anchor, replacement, label) {
  if (source.includes(replacement)) return source;
  if (!source.includes(anchor)) throw new Error(`A2 one-minute knowledge patch anchor missing: ${label}`);
  return source.replace(anchor, replacement);
}

function patchPresenter() {
  let source = fs.readFileSync(presenterPath, "utf8");
  const anchor = `    {\n      id: "warmup",\n      type: "list",\n      kicker: "Warm-up",\n      title: advanced ? "Einstieg" : "Warm-up",\n      items: Array.isArray(slide.warmupQuestionsDe) ? slide.warmupQuestionsDe : [],\n      suggestedMinutes: interactionMinutes(slide, 0) || 5,\n    },\n    {\n      id: "phrases",`;
  const replacement = `    {\n      id: "warmup",\n      type: "list",\n      kicker: "Warm-up",\n      title: advanced ? "Einstieg" : "Warm-up",\n      items: Array.isArray(slide.warmupQuestionsDe) ? slide.warmupQuestionsDe : [],\n      suggestedMinutes: interactionMinutes(slide, 0) || 5,\n    },\n    {\n      id: "knowledge",\n      type: "task",\n      kicker: "1 Minute",\n      title: "1-Minute-Wissen",\n      body: slide.knowledgeTextDe || "",\n      suggestedMinutes: 1,\n    },\n    {\n      id: "phrases",`;
  source = replaceOnce(source, anchor, replacement, "insert knowledge stage after warm-up");
  fs.writeFileSync(presenterPath, source);
}

function patchKnowledgeTexts() {
  const grouped = new Map();
  for (const lesson of A2_KNOWLEDGE_TEXTS) {
    if (!grouped.has(lesson.path)) grouped.set(lesson.path, []);
    grouped.get(lesson.path).push(lesson);
  }

  for (const [relativePath, lessons] of grouped) {
    const filePath = new URL(`../${relativePath}`, import.meta.url);
    let source = fs.readFileSync(filePath, "utf8");

    for (const lesson of lessons) {
      const marker = `    assignmentId: "${lesson.assignmentId}",`;
      const start = source.indexOf(marker);
      if (start === -1) {
        throw new Error(`A2 one-minute knowledge patch anchor missing: ${lesson.assignmentId}`);
      }

      const nextSlide = source.indexOf("\n  {", start + marker.length);
      const end = nextSlide === -1 ? source.length : nextSlide;
      const block = source.slice(start, end);
      if (block.includes("knowledgeTextDe:")) continue;

      const durationAnchor = `    estimatedDuration: "45–60 minutes",`;
      const durationIndexInBlock = block.indexOf(durationAnchor);
      if (durationIndexInBlock === -1) {
        throw new Error(`A2 one-minute knowledge duration anchor missing: ${lesson.assignmentId}`);
      }

      const durationIndex = start + durationIndexInBlock;
      const insertAt = durationIndex + durationAnchor.length;
      const knowledgeLine = `\n    knowledgeTextDe: ${JSON.stringify(lesson.text)},`;
      source = source.slice(0, insertAt) + knowledgeLine + source.slice(insertAt);
    }

    fs.writeFileSync(filePath, source);
  }
}

patchPresenter();
patchKnowledgeTexts();
console.log(`A2 one-minute knowledge slides are wired into Presenter for ${A2_KNOWLEDGE_TEXTS.length} chapters.`);
