import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const dataDir = path.join(__dirname, "data");
const encoded = [1, 2, 3, 4]
  .map((part) => fs.readFileSync(path.join(dataDir, `b2c1-speaking-models-${part}.txt`), "utf8").trim())
  .join("");
const payload = JSON.parse(zlib.gunzipSync(Buffer.from(encoded, "base64")).toString("utf8"));

function jsObject(name, value) {
  return `const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

const generated = [
  "// Generated by scripts/patchB2C1SpeakingModels.mjs. Do not edit by hand.",
  "",
  jsObject("B2_SPEAKING_ANSWERS", payload.B2),
  jsObject("C1_SPEAKING_ANSWERS", payload.C1),
  `function attach(slides = [], answersByDay = {}) {
  for (const slide of slides) {
    const questions = Array.isArray(slide.studentQuestionsDe) ? slide.studentQuestionsDe : [];
    const answers = answersByDay[Number(slide.dayNumber)] || [];
    slide.speakingModels = questions.map((questionDe, index) => ({
      questionDe,
      modelAnswerDe: answers[index] || "",
    }));
  }
}

export function attachAdvancedSpeakingModels({ b2Slides = [], c1Slides = [] } = {}) {
  attach(b2Slides, B2_SPEAKING_ANSWERS);
  attach(c1Slides, C1_SPEAKING_ANSWERS);
}
`,
].join("\n");

const generatedPath = path.join(root, "src/data/advancedSpeakingModels.js");
if (!fs.existsSync(generatedPath) || fs.readFileSync(generatedPath, "utf8") !== generated) {
  fs.writeFileSync(generatedPath, generated, "utf8");
}

function patchFile(relativePath, replacements) {
  const filePath = path.join(root, relativePath);
  let content = fs.readFileSync(filePath, "utf8");
  let changed = false;

  for (const { from, to } of replacements) {
    if (content.includes(to)) continue;
    if (!content.includes(from)) {
      throw new Error(`Unable to patch ${relativePath}: expected text not found: ${from}`);
    }
    content = content.replace(from, to);
    changed = true;
  }

  if (changed) fs.writeFileSync(filePath, content, "utf8");
}

patchFile("src/data/teachingSlides.js", [
  {
    from: 'import { c1PresenterSlides } from "./c1PresenterSlides.js";',
    to: 'import { c1PresenterSlides } from "./c1PresenterSlides.js";\nimport { attachAdvancedSpeakingModels } from "./advancedSpeakingModels.js";',
  },
  {
    from: "const curatedSlides = [",
    to: "attachAdvancedSpeakingModels({ b2Slides: b2PresenterSlides, c1Slides: c1PresenterSlides });\n\nconst curatedSlides = [",
  },
]);

patchFile("src/utils/teachingPresenter.js", [
  {
    from: 'requiresQuestionModel: ["A2", "B1"].includes(String(slide.course || "").toUpperCase()),',
    to: 'requiresQuestionModel: ["A2", "B1", "B2", "C1"].includes(String(slide.course || "").toUpperCase()),',
  },
]);

const b1RegressionPath = path.join(root, "tests/b1-speaking-model-answers.test.js");
if (fs.existsSync(b1RegressionPath)) {
  patchFile("tests/b1-speaking-model-answers.test.js", [
    {
      from: 'for (const level of ["A1", "B2", "C1"]) {',
      to: 'for (const level of ["A1"]) {',
    },
  ]);
}

console.log("B2/C1 speaking models are patched.");
